#! /bin/bash
read -rep $'Enter the name of the file you want to find:\n' file



cd /home


function helper (){
	value=0
	
		for i in $(ls); do {
			if [[ -d "$i" ]]; then
				value=1
				if cd "$i" ; then
                  :
				else
					continue
				fi
				
				#echo "$i"
				pwd
				finder
				helper
			fi
	}
	done
	
	if [[ "$value" -eq 0  ]]; then
		cd ..
	fi

}



function finder(){

for i in $(ls); do

if [[ $file == "$i" ]]; then
	echo "File Here --> $(pwd)"
fi

done

}


helper
